dependencies {
    implementation project(':shared:shared-security')
    implementation project(':shared:shared-messaging')
    implementation project(':shared:shared-observability')
    implementation 'org.springframework.boot:spring-boot-starter-web'


    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    
    // Postgres Driver
    runtimeOnly 'org.postgresql:postgresql'
}
